version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - mysql:mysql
    env_file:
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  data:
      environment:
        MYSQL_DATABASE: 'mysql'
        MYSQL_USER: 'caminomurillo'
        MYSQL_PASSWORD: 'murillo12'
        MYSQL_ROOT_PASSWORD: 'murillo12'
      ports:
        - '3306:3306'
      expose:
        - '3306'
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    command: "true"

  mysql:
    restart: always
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
