version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - sqlite3:sqlite3
    env_file:
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  data:
    environment:
      SQLITE_DATABASE: 'db.sqlite'
      SQLITE_PASSWORD: 'murillo12'
    image: nouchka/sqlite3:latest
    volumes:
      - db-data:/root/db/
    command: "true"

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - db-data:/root/db/

volumes:
  db-data:
