version: "3"

networks:
  backend:
    driver: bridge

volumes:
  my-db:

services:
  flask_app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        BUILD_ENV: $BUILD_ENV
    container_name: flask_app
    expose:
      - '5000'
    environment:
      - FLASK_DEBUG=$FLASK_DEBUG
      - DB_URL=$DB_URL
    ports:
      - "5000:5000"
    network_mode: bridge
  mysql:
    image: mysql:8.0.22
    container_name: mydb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - backend
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql